SWITCH(
  TRUE,
  ISBLANK('Meteorite Landings'[class]),
  "(Blank)",
  'Meteorite Landings'[class] IN {"Acapulcoite",
    "Acapulcoite/Lodranite",
    "Achondrite-ung",
    "Angrite",
    "Aubrite",
    "Aubrite-an",
    "Brachinite",
    "Diogenite",
    "Diogenite-an",
    "Diogenite-olivine",
    "Diogenite-pm",
    "Enst achon-ung",
    "Eucrite",
    "Eucrite-an",
    "Eucrite-br",
    "Eucrite-cm",
    "Eucrite-Mg rich",
    "Eucrite-mmict",
    "Eucrite-pmict",
    "Eucrite-unbr",
    "Fusion crust",
    "Howardite",
    "Lodranite",
    "Lodranite-an",
    "Ureilite",
    "Ureilite-an",
    "Ureilite-pmict",
    "Winonaite"},
  "Achondrites",
  'Meteorite Landings'[class] IN {"C",
    "C1/2-ung",
    "C2",
    "C2-ung",
    "C3-ung",
    "C4",
    "C4/5",
    "C4-ung",
    "C5/6-ung",
    "C6",
    "CBa",
    "CBb",
    "CH/CBb",
    "CH3",
    "Chondrite-fusion crust",
    "Chondrite-ung",
    "CI1",
    "CK3",
    "CK3-an",
    "CK4",
    "CK4/5",
    "CK4-an",
    "CK5",
    "CK5/6",
    "CK6",
    "CM1",
    "CM1/2",
    "CM2",
    "CM-an",
    "CO3",
    "CO3.0",
    "CO3.2",
    "CO3.3",
    "CO3.4",
    "CO3.5",
    "CO3.6",
    "CO3.7",
    "CO3.8",
    "CR",
    "CR1",
    "CR2",
    "CR2-an",
    "CR-an",
    "CV2",
    "CV3",
    "CV3-an"},
  "Carbonaceous Chondrites",
  'Meteorite Landings'[class] IN {"E",
    "E3",
    "E3-an",
    "E4",
    "E5",
    "E5-an",
    "E6",
    "E-an",
    "EH",
    "EH3",
    "EH3/4-an",
    "EH4",
    "EH4/5",
    "EH5",
    "EH6",
    "EH6-an",
    "EH7",
    "EH7-an",
    "EH-imp melt",
    "EL3",
    "EL4",
    "EL4/5",
    "EL5",
    "EL6",
    "EL6/7",
    "EL7"},
  "Enstatite Chondrites",
  'Meteorite Landings'[class] IN {"Iron",
    "Iron, IAB complex",
    "Iron, IAB?",
    "Iron, IAB-an",
    "Iron, IAB-MG",
    "Iron, IAB-sHH",
    "Iron, IAB-sHL",
    "Iron, IAB-sLH",
    "Iron, IAB-sLL",
    "Iron, IAB-sLM",
    "Iron, IAB-ung",
    "Iron, IC",
    "Iron, IC-an",
    "Iron, IIAB",
    "Iron, IIAB-an",
    "Iron, IIC",
    "Iron, IID",
    "Iron, IID-an",
    "Iron, IIE",
    "Iron, IIE-an",
    "Iron, IIF",
    "Iron, IIG",
    "Iron, IIIAB",
    "Iron, IIIAB?",
    "Iron, IIIAB-an",
    "Iron, IIIE",
    "Iron, IIIE-an",
    "Iron, IIIF",
    "Iron, IVA",
    "Iron, IVA-an",
    "Iron, IVB",
    "Iron, ungrouped",
    "Relict iron"},
  "Irons",
  'Meteorite Landings'[class] IN {"K",
    "K3"},
  "Kakangari",
  'Meteorite Landings'[class] IN {"Lunar",
    "Lunar (anorth)",
    "Lunar (bas. breccia)",
    "Lunar (bas/anor)",
    "Lunar (basalt)",
    "Lunar (feldsp. breccia)",
    "Lunar (gabbro)",
    "Lunar (norite)"},
  "Lunar",
  'Meteorite Landings'[class] IN {"Martian (chassignite)",
    "Martian (nakhlite)",
    "Martian (OPX)",
    "Martian (shergottite)"},
  "Martian",
  'Meteorite Landings'[class] IN {"Mesosiderite",
    "Mesosiderite?",
    "Mesosiderite-A",
    "Mesosiderite-A1",
    "Mesosiderite-A2",
    "Mesosiderite-A3",
    "Mesosiderite-A3/4",
    "Mesosiderite-A4",
    "Mesosiderite-an",
    "Mesosiderite-B",
    "Mesosiderite-B1",
    "Mesosiderite-B2",
    "Mesosiderite-B4",
    "Mesosiderite-C",
    "Mesosiderite-C2"},
  "Mesosiderites",
  'Meteorite Landings'[class] IN {"H",
    "H(?)4",
    "H(5?)",
    "H(L)3",
    "H(L)3-an",
    "H/L~4",
    "H/L3",
    "H/L3.5",
    "H/L3.6",
    "H/L3.9",
    "H/L4",
    "H/L4-5",
    "H/L5",
    "H/L6",
    "H?",
    "H~4",
    "H~4/5",
    "H~5",
    "H~6",
    "H3",
    "H3.0",
    "H3.0-3.4",
    "H3.1",
    "H3.10",
    "H3.2",
    "H3.2-3.7",
    "H3.2-6",
    "H3.2-an",
    "H3.3",
    "H3.4",
    "H3.4/3.5",
    "H3.4-5",
    "H3.5",
    "H3.5-4",
    "H3.6",
    "H3.6-6",
    "H3.7",
    "H3.7/3.8",
    "H3.7-5",
    "H3.7-6",
    "H3.8",
    "H3.8/3.9",
    "H3.8/4",
    "H3.8-4",
    "H3.8-5",
    "H3.8-6",
    "H3.8-an",
    "H3.9",
    "H3.9/4",
    "H3.9-5",
    "H3.9-6",
    "H3/4",
    "H3-4",
    "H3-5",
    "H3-6",
    "H3-an",
    "H4",
    "H4(?)",
    "H4/5",
    "H4/6",
    "H4-5",
    "H4-6",
    "H4-an",
    "H5",
    "H5/6",
    "H5-6",
    "H5-7",
    "H5-an",
    "H5-melt breccia",
    "H6",
    "H6-melt breccia",
    "H7",
    "H-an",
    "H-imp melt",
    "H-melt rock",
    "H-metal",
    "L",
    "L(?)3",
    "L(LL)3",
    "L(LL)3.05",
    "L(LL)3.5-3.7",
    "L(LL)5",
    "L(LL)6",
    "L/LL",
    "L/LL(?)3",
    "L/LL~4",
    "L/LL~5",
    "L/LL~6",
    "L/LL3",
    "L/LL3.10",
    "L/LL3.2",
    "L/LL3.4",
    "L/LL3.6/3.7",
    "L/LL3-5",
    "L/LL3-6",
    "L/LL4",
    "L/LL4/5",
    "L/LL4-6",
    "L/LL5",
    "L/LL5/6",
    "L/LL5-6",
    "L/LL6",
    "L/LL6-an",
    "L~3",
    "L~4",
    "L~5",
    "L~6",
    "L3",
    "L3.0",
    "L3.0-3.7",
    "L3.0-3.9",
    "L3.05",
    "L3.1",
    "L3.10",
    "L3.2",
    "L3.2-3.5",
    "L3.2-3.6",
    "L3.3",
    "L3.3-3.5",
    "L3.3-3.6",
    "L3.3-3.7",
    "L3.4",
    "L3.4-3.7",
    "L3.5",
    "L3.5-3.7",
    "L3.5-3.8",
    "L3.5-3.9",
    "L3.5-5",
    "L3.6",
    "L3.6-4",
    "L3.7",
    "L3.7/3.8",
    "L3.7-3.9",
    "L3.7-4",
    "L3.7-6",
    "L3.8",
    "L3.8-6",
    "L3.8-an",
    "L3.9",
    "L3.9/4",
    "L3.9-5",
    "L3.9-6",
    "L3/4",
    "L3-4",
    "L3-5",
    "L3-6",
    "L4",
    "L4/5",
    "L4-5",
    "L4-6",
    "L4-an",
    "L5",
    "L5/6",
    "L5-6",
    "L5-7",
    "L6",
    "L6/7",
    "L6-melt breccia",
    "L7",
    "L-imp melt",
    "LL",
    "LL(L)3",
    "LL~3",
    "LL~5",
    "LL~6",
    "LL3",
    "LL3.0",
    "LL3.00",
    "LL3.1",
    "LL3.1-3.5",
    "LL3.15",
    "LL3.2",
    "LL3.3",
    "LL3.4",
    "LL3.5",
    "LL3.6",
    "LL3.7",
    "LL3.7-6",
    "LL3.8",
    "LL3.8-6",
    "LL3.9",
    "LL3.9/4",
    "LL3/4",
    "LL3-5",
    "LL3-6",
    "LL4",
    "LL4/5",
    "LL4-5",
    "LL4-6",
    "LL5",
    "LL5/6",
    "LL5-6",
    "LL5-7",
    "LL6",
    "LL6(?)",
    "LL7",
    "LL7(?)",
    "L-melt breccia",
    "L-melt rock",
    "L-metal",
    "OC",
    "Relict H",
    "Relict OC"},
  "Ordinary Chondrites",
  'Meteorite Landings'[class] IN {"Pallasite",
    "Pallasite, PES",
    "Pallasite, PMG",
    "Pallasite, PMG-an",
    "Pallasite, ungrouped",
    "Pallasite?"},
  "Pallasites",
  'Meteorite Landings'[class] IN {"R",
    "R3",
    "R3.5-6",
    "R3.6",
    "R3.8",
    "R3.8-5",
    "R3.8-6",
    "R3.9",
    "R3-4",
    "R3-6",
    "R4",
    "R5"},
  "Rumurutiites",
  'Meteorite Landings'[class] IN {"Stone-uncl",
    "Stone-ung"},
  "Stone",
  'Meteorite Landings'[class] IN {"Unknown"},
  "Unknown",
  'Meteorite Landings'[class]
)