SWITCH(
  TRUE,
  ISBLANK('Meteorite Landings'[composition]),
  "(Blank)",
  'Meteorite Landings'[composition] IN {"Achondrites",
    "Lunar",
    "Martian"},
  "Achondrites",
  'Meteorite Landings'[composition] IN {"Carbonaceous Chondrites",
    "Enstatite Chondrites",
    "Kakangari",
    "Ordinary Chondrites",
    "Rumurutiites"},
  "Chondrites",
  'Meteorite Landings'[composition] IN {"Irons"},
  "Irons",
  'Meteorite Landings'[composition] IN {"Stone"},
  "Stone",
  'Meteorite Landings'[composition] IN {"Mesosiderites",
    "Pallasites"},
  "Stony Irons",
  'Meteorite Landings'[composition] IN {"Unknown"},
  "Unknown",
  'Meteorite Landings'[composition]
)